/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MoneyV2 = IDL.Record({
  'currencyCode' : IDL.Text,
  'amount' : IDL.Text,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Text,
  'variantId' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : MoneyV2,
});
export const ShippingAddress = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'state' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
});
export const OrderDetails = IDL.Record({
  'totalAmount' : IDL.Float64,
  'shippingAddress' : ShippingAddress,
  'items' : IDL.Vec(CartItem),
  'orderNumber' : IDL.Text,
});
export const ProductImage = IDL.Record({
  'url' : IDL.Text,
  'altText' : IDL.Text,
});
export const ProductVariant = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'color' : IDL.Text,
  'size' : IDL.Text,
  'price' : MoneyV2,
  'availableForSale' : IDL.Bool,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'featuredImage' : ProductImage,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'collections' : IDL.Vec(IDL.Text),
  'variants' : IDL.Vec(ProductVariant),
  'handle' : IDL.Text,
  'images' : IDL.Vec(ProductImage),
});

export const idlService = IDL.Service({
  'buildCheckoutUrl' : IDL.Func([IDL.Vec(CartItem)], [IDL.Text], ['query']),
  'createOrder' : IDL.Func([OrderDetails], [IDL.Text], []),
  'getOrders' : IDL.Func([], [IDL.Vec(OrderDetails)], ['query']),
  'getProductByHandle' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCollection' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Product)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MoneyV2 = IDL.Record({
    'currencyCode' : IDL.Text,
    'amount' : IDL.Text,
  });
  const CartItem = IDL.Record({
    'productId' : IDL.Text,
    'variantId' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : MoneyV2,
  });
  const ShippingAddress = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'state' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const OrderDetails = IDL.Record({
    'totalAmount' : IDL.Float64,
    'shippingAddress' : ShippingAddress,
    'items' : IDL.Vec(CartItem),
    'orderNumber' : IDL.Text,
  });
  const ProductImage = IDL.Record({ 'url' : IDL.Text, 'altText' : IDL.Text });
  const ProductVariant = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'color' : IDL.Text,
    'size' : IDL.Text,
    'price' : MoneyV2,
    'availableForSale' : IDL.Bool,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'featuredImage' : ProductImage,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'collections' : IDL.Vec(IDL.Text),
    'variants' : IDL.Vec(ProductVariant),
    'handle' : IDL.Text,
    'images' : IDL.Vec(ProductImage),
  });
  
  return IDL.Service({
    'buildCheckoutUrl' : IDL.Func([IDL.Vec(CartItem)], [IDL.Text], ['query']),
    'createOrder' : IDL.Func([OrderDetails], [IDL.Text], []),
    'getOrders' : IDL.Func([], [IDL.Vec(OrderDetails)], ['query']),
    'getProductByHandle' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCollection' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };