/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem {
  'productId' : string,
  'variantId' : string,
  'quantity' : bigint,
  'price' : MoneyV2,
}
export interface MoneyV2 { 'currencyCode' : string, 'amount' : string }
export interface OrderDetails {
  'totalAmount' : number,
  'shippingAddress' : ShippingAddress,
  'items' : Array<CartItem>,
  'orderNumber' : string,
}
export interface Product {
  'id' : string,
  'title' : string,
  'featuredImage' : ProductImage,
  'tags' : Array<string>,
  'description' : string,
  'collections' : Array<string>,
  'variants' : Array<ProductVariant>,
  'handle' : string,
  'images' : Array<ProductImage>,
}
export interface ProductImage { 'url' : string, 'altText' : string }
export interface ProductVariant {
  'id' : string,
  'title' : string,
  'color' : string,
  'size' : string,
  'price' : MoneyV2,
  'availableForSale' : boolean,
}
export interface ShippingAddress {
  'city' : string,
  'name' : string,
  'state' : string,
  'address' : string,
  'phone' : string,
  'pincode' : string,
}
export interface _SERVICE {
  'buildCheckoutUrl' : ActorMethod<[Array<CartItem>], string>,
  'createOrder' : ActorMethod<[OrderDetails], string>,
  'getOrders' : ActorMethod<[], Array<OrderDetails>>,
  'getProductByHandle' : ActorMethod<[string], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCollection' : ActorMethod<[string], Array<Product>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];